title: "Half Fast Notes"
description: "A DevOps should be neither fast nor slow."
baseurl: "" # change if served from a subpath
url: "https://half-fast-devops.github.io"     # set to your site URL if available
theme: jekyll-theme-minimal
markdown: kramdown

plugins:
  - jekyll-feed

collections: {}

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Assets path
sass:
  style: compressed
